matrix:
  include:
    - language: c
      os: windows
      script:
        - cd build
        - cd vs2010
        - msbuild /p:Configuration="Release|x64" NativeFileDialog.sln

    - language: c
      os: linux
      before_install:
        - sudo apt-get install -y libgtk-3-dev
      script:
        - cd build/gmake_linux
        - make config=release_x64

    - language: objective_c
      os: osx
      script:
        - cd build/gmake_macosx
        - make config=release_x64
      # branches:
      #   only:
      #     - devel
      #     - master
