matrix:
  include:
    - language: cpp
      os: windows
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - ./build.cmd

    - language: c
      os: linux
      before_install:
        - sudo apt-get install -y libgtk-3-dev
        - cd build/gmake_linux
      script:
        - make config=release_x64

    - language: objective_c
      os: osx
      before_install:
        - cd build/gmake_macosx
      script:
        - make config=release_x64
      # branches:
      #   only:
      #     - devel
      #     - master
